name: smart_travel_planning_appli
description: Flutter application for travel plans.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  google_fonts: ^1.1.0
  smooth_page_indicator: ^0.1.5

  flutter_icons: ^1.0.0

  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  google_sign_in: ^4.0.1+1
  alert_dialog: ^1.0.0
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - images/stpa.png
    - images/ftravel.jpg
    - images/travel.png
    - images/btravel.jpg
    - images/stbg.jpg
    - images/cctravel.jpg




